import { Lora  } from "next/font/google";
import "./globals.css";


const lora = Lora({ subsets: ["latin"]});


export const metadata = {
  title: "Leandro Magallanes - CV",
  description: "Generated by create next app for PatagoniaScript",
  

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lora.className}>{children}</body>
    </html>
  );
}
